### ISSUE TITLE
Can this be a method?

### ISSUE THREAD

**Issue by AlexKap23** [dccl90/QuizMaker#2]
https://github.com/dccl90/QuizMaker/blob/a79d8cfa681aa13d53f03067e8d1cc041f72694e/QuizBuilder/Program.cs#L30-L53

This block of coding is adding questions in a list, in order to be saved to the file. It can be hidden inside a method. It can also be broken down more into 2 methods 1 for the actual questions and one for the available options for this question.

**Comment by dccl90** [comment]
Split code up into UI methods
