### ISSUE TITLE
Consider replacing your class name

### ISSUE THREAD

**Issue by AlexKap23** [dccl90/QuizMaker#3]
https://github.com/dccl90/QuizMaker/blob/990aebdbcc139dd4cf02764ba3dc6c8fd9b5f062/QuizBuilder/Strings.cs#L5

Strings is not a good name for a class. To start with, String is a reserved word and other than that you are not saving strings but messages. 
So consider renaming it to something else.

**Comment by dccl90** [comment]
Updated class name
