### ISSUE TITLE
What will happen if questionList is null?

### ISSUE THREAD

**Issue by AlexKap23** [dccl90/QuizMaker#4]
https://github.com/dccl90/QuizMaker/blob/990aebdbcc139dd4cf02764ba3dc6c8fd9b5f062/QuizBuilder/Program.cs#L29

Your ReadXmlFile() method is checking if the file exists and if it doesn't it returns back a null value. But on your program you are never checking for null. So trying to get .Count of a null value will produce an exception. 

This should be handled.

**Comment by dccl90** [comment]
Added check to see if the file is null and print a message.
