### ISSUE TITLE
Naming is questionable.

### ISSUE THREAD

**Issue by AlexKap23** [dccl90/QuizMaker#5]
https://github.com/dccl90/QuizMaker/blob/990aebdbcc139dd4cf02764ba3dc6c8fd9b5f062/QuizBuilder/UserInterface.cs#L11

this method is actually getting user's selection and not setting it so this name seems a little missleading. I would go with a name that is more descriptive and catchy like, collectUserAnsewer or something similar.

**Comment by dccl90** [comment]
Updated name
