### ISSUE TITLE
Don't create a new Random variable for each method call

### ISSUE THREAD

**Issue by incredibleLeitman** [dccl90/QuizMaker#6]
https://github.com/dccl90/QuizMaker/blob/f3058667a98e2f13fd426b570199c8a4a8fd8d2f/QuizBuilder/QuizLogic.cs#L169
Instead you can either have one commonly used instance for all your project if you make use of random in multiple files
or you can just make a class field that gets initialized when the class gets created

**Comment by dccl90** [comment]
Fixed
